vim.keymap.set('n', '<leader>db', '<cmd>lua require"dap".toggle_breakpoint()<cr>')
vim.keymap.set('n', '<leader>dc', '<cmd>lua require"dap".continue()<cr>')
vim.keymap.set('n', '<leader>dn', '<cmd>lua require"dap".step_over()<cr>')
vim.keymap.set('n', '<leader>ds', '<cmd>lua require"dap".step_into()<cr>')
vim.keymap.set('n', '<leader>do', '<cmd>lua require"dap".step_out()<cr>')
vim.keymap.set('n', '<leader>dr', '<cmd>lua require"dap".repl.toggle()<cr>')
vim.keymap.set('n', '<leader>dl', '<cmd>lua require"dap".run_last()<cr>')
vim.keymap.set('n', '<leader>du', '<cmd>lua require"dap.ui.variables".hover()<cr>')
vim.keymap.set('n', '<leader>di', '<cmd>lua require"dap.ui.widgets".hover()<cr>')
vim.keymap.set('n', '<leader>dt', '<cmd>lua require"dap".toggle()<cr>')
vim.keymap.set('n', '<leader>dp', '<cmd>lua require"dap".pause.toggle()<cr>')
vim.keymap.set('n', '<leader>de', '<cmd>lua require"dap".set_exception_breakpoints()<cr>')
vim.keymap.set('n', '<leader>dk', '<cmd>lua require"dap".close()<cr>')
vim.keymap.set('n', '<leader>dx', '<cmd>lua require"dap".run_to_cursor()<cr>')
vim.keymap.set('n', '<leader>df', '<cmd>lua require"dap".run_to_function()<cr>')

